version: '2'

services:
  api2cms-src:
    container_name: api2cms-src
    image: busybox
    volumes:
        - ./:/usr/share/nginx/html/
  api2cms-nginx:
    image: nginx:latest
    container_name: api2cms-nginx
    ports:
      - "8080:80"
    volumes:
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - api2cms-src
    depends_on:
      - "api2cms-src"
      - "api2cms-php-fpm"

  api2cms-php-fpm:
    build:
      context: ./images/php-fpm
    container_name: api2cms-php-fpm
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes_from:
      - api2cms-src
    depends_on:
      - "api2cms-src"

  api2cms-pgsql:
    image: postgres:latest
    container_name: api2cms-pgsql
    volumes:
      - /var/lib/pgsql
      - ./images/pgsql/init-user-db.sh:/docker-entrypoint-initdb.d/1.init-user-db.sh
      - ./schema/db.sql:/tmp/api2cms.sql
